name: Deploy to S3

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the action.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Optional: Install AWS CLI (if it's not already installed)
    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    # Configure AWS credentials from GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Specify your region

    # Sync files to S3
    - name: Deploy to S3
      run: aws s3 sync ./public s3://your-s3-bucket-name --delete
