name: Deploy to S3

on:
  push:
    branches:
      - main  # The workflow will trigger on push to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # The workflow runs on a GitHub-hosted runner with an Ubuntu image

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # Action to check out the repository's code into the runner

      # Optional: Install AWS CLI (if it's not already installed) 
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2  # Setup Node.js in the GitHub runner
        with:
          node-version: '14'  # Node.js version 14 is being used here. Modify as per your project's requirement.

      # Step 3: Install project dependencies using npm
      - name: Install dependencies
        run: npm install  # This command will install all the dependencies specified in package.json

      # Step 4: Build the project
      - name: Build the project
        run: npm run build  # This command runs the build script in your project, typically outputting to a 'build/' directory

      # Step 5: Modify paths in index.html for AWS
      - name: Modify paths for AWS deployment
        run: |
          sed -i 's|/box-office/logo192.png|logo192.png|g' ./build/index.html
          sed -i 's|/box-office/manifest.json|manifest.json|g' ./build/index.html
          sed -i 's|/box-office/static/js/main.[a-z0-9]*.js|static/js/main.9d9e34d0.js|g' ./build/index.html
          sed -i 's|/box-office/static/css/main.[a-z0-9]*.css|static/css/main.b2586571.css|g' ./build/index.html

      # Step 6: Deploy the built files to AWS S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key ID from GitHub Secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key from GitHub Secrets
          AWS_REGION: ${{ secrets.AWS_REGION }}  # AWS region stored in GitHub Secrets (e.g., 'us-east-1')
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}  # S3 bucket name stored in GitHub Secrets
        run: |
          aws s3 sync build/ s3://$S3_BUCKET --delete --cache-control "max-age=31536000"
          aws s3 cp s3://$S3_BUCKET/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache" --content-type "text/html" --metadata-directive REPLACE
