name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Remove `/box-office/` prefix from paths in index.html
      - name: Modify paths for AWS deployment
        run: sed -i 's|/box-office/||g' ./build/index.html

      # Step 6: Sync the built files to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync build/ s3://$S3_BUCKET --delete --cache-control "max-age=31536000"
          aws s3 cp s3://$S3_BUCKET/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache" --content-type "text/html" --metadata-directive REPLACE
